name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  DATABASE: mongodb://root:example@localhost:27017/championship?authSource=admin
  REDIS: redis://localhost:6379/

jobs:
  build:

    runs-on: ubuntu-latest
    services:
          mongodb:
              image: mongo
              env:
                MONGO_INITDB_ROOT_USERNAME: root
                MONGO_INITDB_ROOT_PASSWORD: example
                MONGO_INITDB_DATABASE: league
              ports:
                - 27017:27017
          redis:
            image: redis
            ports:
              - 6372
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
